# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceries',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='groceries',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
